/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        long time = System.currentTimeMillis();
        System.out.println(Long.toBinaryString(time).length());
        System.out.println(Long.toBinaryString(time << 22));
        System.out.println(Long.toBinaryString(1023 << 12));
        System.out.println(Long.toBinaryString(4095));

        System.out.println(Long.toBinaryString(time << 22 | 1023 << 12 | 4095));
    }
}
