import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

//        System.out.println(uuid.version());
//        System.out.println(uuid.clockSequence());
//        System.out.println(uuid.getLeastSignificantBits());
//        System.out.println(uuid.getMostSignificantBits());
//        System.out.println(uuid.node());
        for(int i = 0; i < 100; i ++) {
            System.out.println();
        }

    }
}
