package projecteuler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class EvenFibonacciNumbers {

    public long evenSum(int max) {
        int[] f = new int[2];
        f[0] = 1;
        f[1] = 2;
        long sum = f[1];
        while (f[0] + f[1] <= max) {
            int tmp = f[1];
            f[1] = f[0] + f[1];
            f[0] = tmp;
            if (f[1] % 2 == 0) sum += f[1];
        }
        return sum;
    }
}
